### ISSUE TITLE
Hide constant statepoint parameters on the statepoint parameters card

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/signac-dashboard#76]
### Feature description

It would be nice if there was an option to hide the statepoint parameters that are constant across all jobs in the Statepoint Parameters card. This would be especially useful in the exploration stages of a project when you add sp params that you think may change but have only initialized a subset of all possible jobs.

### Proposed solution

I'm not sure how all of this works on the back end, but it's just loading a signac project somewhere, so there should be a way to call `project.detect_schema(exclude_const=True)` and pass that information along to wherever it needs to go.

**Comment by bdice** [comment]
Here's my best estimation of how this could be implemented in < 30 minutes:
1. Modify `modules/statepoint_list.py` so that the `__init__` function takes another argument, `exclude_const=False`.
2. Set the boolean `self.exclude_const = exclude_const` and create an empty list `self.variable_keys= []` in the `__init__` function.
3. Add a registration method to the `StatepointList` class, `def register(self, dashboard)`, that accesses the dashboard object, executes `dashboard.project.detect_schema(exclude_const=True)` and sets `self.variable_keys = [...all the keys in the schema...]`
4. Modify `def get_cards(self, job)` to only include variable keys, or use all keys if `len(self.variable_keys) == 0`. (This is just my preference -- otherwise projects with one job would have no content, which seems weird to me.)

**Comment by tcmoore3** [comment]
I'm closing this issue for the same reason I closed #89.
